[package]
name = "fast-crawler"
version = "0.1.0"
authors = ["Julian Szczurowski <julian.szczurowski@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
hyper = "0.12.13"
tokio-executor = "0.1.5"
futures = "0.1.0"

[dev-dependencies]
pretty_assertions = "0.4.0"
